In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
import pandas as pd
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

In [4]:
from sklearn.svm import SVC
model = SVC(kernel='linear', C=30, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

Exercise

In [5]:
from sklearn.datasets import load_digits
digits = load_digits()

In [6]:
df = pd.DataFrame(data=digits.data, columns=digits.feature_names)
df['digit'] = digits.target
df['digit'] = df['digit'].apply(lambda x: digits.target_names[x])
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,digit
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

Grid Search CV

In [8]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(), {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel' : ['rbf', 'linear']}, cv=5)
clf.fit(digits.data, digits.target)
#clf.cv_results_
df = pd.DataFrame(clf.cv_results_)
df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.047651,0.004778,0.030068,0.005604,1,0.0010,rbf,"{'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}",0.975000,0.950000,0.983287,0.991643,0.961003,0.972187,0.015013,1
1,0.024017,0.000994,0.002364,0.003413,1,0.0010,linear,"{'C': 1, 'gamma': 0.001, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,8
2,0.037198,0.006458,0.033696,0.005333,1,0.0001,rbf,"{'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}",0.936111,0.933333,0.969359,0.980501,0.916435,0.947148,0.023924,16
3,0.022577,0.005958,0.005523,0.004430,1,0.0001,linear,"{'C': 1, 'gamma': 0.0001, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,8
4,0.051455,0.005639,0.030410,0.003481,10,0.0010,rbf,"{'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}",0.977778,0.950000,0.983287,0.986072,0.963788,0.972185,0.013491,2

In [9]:
df[['param_C', 'param_gamma', 'param_kernel', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False).head(10)

    param_C  param_gamma param_kernel  mean_test_score
0         1       0.0010          rbf         0.972187
4        10       0.0010          rbf         0.972185
8       100       0.0010          rbf         0.972185
12     1000       0.0010          rbf         0.972185
10      100       0.0001          rbf         0.962165
14     1000       0.0001          rbf         0.962165
6        10       0.0001          rbf         0.959943
1         1       0.0010       linear         0.947697
3         1       0.0001       linear         0.947697
5        10       0.0010       linear         0.947697

In [10]:
clf.best_params_

{'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}

In [11]:
clf.best_score_

0.9721866295264624

Randomied Search  CV

In [12]:
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(SVC(gamma='auto'), {'C': [1, 10, 100, 1000], 'kernel' : ['rbf', 'linear']}, cv=5, n_iter=7)
clf.fit(digits.data, digits.target)
df = pd.DataFrame(clf.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]
df

   param_C param_kernel  mean_test_score
0      100       linear         0.947697
1        1       linear         0.947697
2        1          rbf         0.448545
3     1000       linear         0.947697
4     1000          rbf         0.476366
5       10       linear         0.947697
6      100          rbf         0.476366

Different models with different hyper parameters

In [13]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear'],
            'degree': [3, 5],  # for poly kernel (if used)
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [10, 50, 100],
            'max_depth': [None, 5, 10],
            'min_samples_split': [2, 5],
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {
            'C': [0.1, 1, 10],
            'penalty': ['l1', 'l2']
        }
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'max_depth': [None, 5, 10, 20],
            'min_samples_split': [2, 5, 10],
            'criterion': ['gini', 'entropy']
        }
    },
    'gaussian_nb': {
        'model': GaussianNB(),
        'params': {
            # GaussianNB usually has no tunable hyperparameters, but you can test priors
            'var_smoothing': [1e-9, 1e-8, 1e-7]
        }
    },
    'multinomial_nb': {
        'model': MultinomialNB(),
        'params': {
            'alpha': [0.5, 1.0, 1.5],
            'fit_prior': [True, False]
        }
    }
}

In [14]:
import warnings
warnings.filterwarnings('ignore')

scores = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(digits.data, digits.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

df = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df.sort_values(by='best_score', ascending=False)

,model,best_score,best_params
0,svm,0.947697,"{'C': 1, 'degree': 3, 'kernel': 'linear'}"
1,random_forest,0.942699,"{'max_depth': 10, 'min_samples_split': 2, 'n_e..."
2,logistic_regression,0.929903,"{'C': 0.1, 'penalty': 'l1'}"
5,multinomial_nb,0.870907,"{'alpha': 1.5, 'fit_prior': True}"
4,gaussian_nb,0.832518,{'var_smoothing': 1e-07}
3,decision_tree,0.812482,"{'criterion': 'entropy', 'max_depth': 10, 'min..."